#!/usr/bin/env bash

set -ex

NAMESPACE=${NAMESPACE:-tugboat}

DOCKERFILE=$1
pushd $(dirname $DOCKERFILE)

echo Building docker image from $DOCKERFILE

NAME=$(cat NAME)
TAG=$(cat TAGS | cut -d' ' -f1)
ALIASES=$(cat TAGS | cut -d' ' -f2-)
IMAGE=${NAMESPACE}/${NAME}:${TAG}

docker build --pull -t $IMAGE .

# Strip volumes
TEMP=$(mktemp -d)
docker save $IMAGE | tar -C "${TEMP}" -x
CONFIG=`jq -r '.[0].Config' "${TEMP}/manifest.json"`
jq 'del(.config.Volumes,.config.Entrypoint)' "${TEMP}/${CONFIG}" > "${TEMP}/config.json"
mv "${TEMP}/config.json" "${TEMP}/${CONFIG}"
tar -C "${TEMP}" -c . | docker load
rm -rf "${TEMP}"

for ALIAS in ${ALIASES}; do
    docker tag ${IMAGE} ${NAMESPACE}/${NAME}:${ALIAS}
done

popd