#!/usr/bin/env bash

set -e

NAMESPACE=${NAMESPACE:-tugboatqa}

DIR="services/$1"

if [ -e "${DIR}/manifest" ]; then
    source "${DIR}/manifest"
fi

NAME=${NAME:-$1}
SERVICE=${SERVICE:-$NAME}
# Read in the CSV and convert to an array.
IFS=',' read -r -a ADDL_PLATFORMS <<< "$ADDL_PLATFORMS"

BUILDX_NAME="$NAMESPACE-$NAME"
# Use builder, or create a new builder, and bootstrap it.
docker buildx use "$BUILDX_NAME" 2>/dev/null || docker buildx create --use --bootstrap --name "$BUILDX_NAME"

build() {
    PLATFORM="$1"

    echo Building "$PLATFORM" docker image from "$DOCKERFILE"

    TEMP=$(mktemp -d)
    docker buildx build --platform "$PLATFORM" --output type=docker,dest="${TEMP}/out.tar" --pull .

    # Strip volumes
    tar -C "${TEMP}" -xf "${TEMP}/out.tar"
    rm -f "${TEMP}/out.tar"
    CONFIG=$(jq -r '.[0].Config' "${TEMP}/manifest.json")
    jq 'del(.config.Volumes,.config.Entrypoint)' "${TEMP}/${CONFIG}" > "${TEMP}/config.json"
    mv -f "${TEMP}/config.json" "${TEMP}/${CONFIG}"
    tar -C "${TEMP}" -c . | docker image import --platform "$PLATFORM" - "$IMAGE"
    rm -rf "${TEMP}"
}

for DOCKERFILE in images/"${SERVICE}"/**/Dockerfile; do
    pushd "$(dirname "$DOCKERFILE")"

    NAME=$(cat NAME)
    TAG=$(cut -d' ' -f1 < TAGS)
    # shellcheck disable=SC2207
    ALIASES=($(cut -d' ' -f2- < TAGS))
    # Prefix each alias with the namespace and name
    ALIASES=("${ALIASES[@]/#/${NAMESPACE}/${NAME}:}")
    IMAGE=${NAMESPACE}/${NAME}:${TAG}

    # Build the default platform image for amd64.
    build linux/amd64

    for ALIAS in "${ALIASES[@]}"; do
        docker tag "${IMAGE}" "${ALIAS}"
    done

    # Build additional platforms if defined, but only if we are pushing.
    if [[ -n "${ADDL_PLATFORMS[*]}" ]] && [[ "$push_and_rm" = 1 ]]; then
        ROOT_MANIFEST=$IMAGE
        PLATFORM_TAGS=()
        for PLATFORM in "${ADDL_PLATFORMS[@]}"; do
            # Add a suffix to the tag with the platform, e.g. "-linux-arm64"
            TAG="$(cut -d' ' -f1 < TAGS)-${PLATFORM//\//-}"
            IMAGE=${NAMESPACE}/${NAME}:${TAG}
            PLATFORM_TAGS+=("$IMAGE")
            build "$PLATFORM"
        done
        docker push --all-tags "${NAMESPACE}/${NAME}"

        # Iterate over all of the tags for this image and create manifest lists
        # with the platform tags.
        for MANIFEST in "$ROOT_MANIFEST" "${ALIASES[@]}"; do
            echo "Creating multi-platform manifest list $MANIFEST to add ${PLATFORM_TAGS[*]}"
            docker manifest rm "$MANIFEST" 2>/dev/null || true
            docker manifest create "$MANIFEST" "$MANIFEST" "${PLATFORM_TAGS[@]}"
            docker manifest push "$MANIFEST"
            docker manifest rm "$MANIFEST"
        done
        # shellcheck disable=SC2046
        docker rmi --force $(docker images ls --filter=reference="${NAMESPACE}/${NAME}" -q | sort | uniq)
    fi

    popd
done

# If we didn't have other platforms to build, push all tags and clean up.
if [[ "$push_and_rm" = 1 ]] && [[ -z "${ADDL_PLATFORMS[*]}" ]]; then
    docker push --all-tags "${NAMESPACE}/${NAME}"
    # shellcheck disable=SC2046
    docker rmi --force $(docker images ls --filter=reference="${NAMESPACE}/${NAME}" -q | sort | uniq)
fi

# Clean up the buildx builder when we're done.
docker buildx rm --force "$BUILDX_NAME" 2>/dev/null || true
