#!/usr/bin/env bash

NAMESPACE=${NAMESPACE:-tugboat}

DIR="services/$1"

if [ -e "${DIR}/manifest" ]; then
    source "${DIR}/manifest"
fi

NAME=${NAME:-$1}
SERVICE=${SERVICE:-$NAME}

for DOCKERFILE in $(find "images/${SERVICE}" -name Dockerfile); do
    pushd $(dirname $DOCKERFILE)

    echo Building docker image from $DOCKERFILE

    NAME=$(cat NAME)
    TAG=$(cat TAGS | cut -d' ' -f1)
    ALIASES=$(cat TAGS | cut -d' ' -f2-)
    IMAGE=${NAMESPACE}/${NAME}:${TAG}

    docker build --pull -t $IMAGE .

    # Strip volumes
    TEMP=$(mktemp -d)
    docker save $IMAGE | tar -C "${TEMP}" -x
    CONFIG=`jq -r '.[0].Config' "${TEMP}/manifest.json"`
    jq 'del(.config.Volumes,.config.Entrypoint)' "${TEMP}/${CONFIG}" > "${TEMP}/config.json"
    mv "${TEMP}/config.json" "${TEMP}/${CONFIG}"
    tar -C "${TEMP}" -c . | docker load
    rm -rf "${TEMP}"

    for ALIAS in ${ALIASES}; do
        docker tag ${IMAGE} ${NAMESPACE}/${NAME}:${ALIAS}
    done

    popd
done