#!/usr/bin/env bash

set -ex

DIR="services/$1"

if [ -e "${DIR}/manifest" ]; then
    source "${DIR}/manifest"
fi

SERVICE=$1
NAME=${NAME:-$1}
FROM=${FROM:-$NAME}
FILTER=${FILTER:-cat}

echo $FILTER

function getTags() {
    SOURCE="${SOURCE:-https://raw.githubusercontent.com/docker-library/official-images/master/library/${NAME}}"
    curl --silent --location --fail --retry 3 "${SOURCE}" | \
        grep Tags | \
        sed 's/^.*Tags: //g' | \
        grep -v -e alpine -e slim -e onbuild -e windows -e wheezy -e nanoserver | \
        ${FILTER} | \
        sed 's/, /:/' | \
        sed 's/, /,/g' | \
        sort
}

function getAliases() {
    TAGS=$1
    if $(echo "$TAGS" | grep -q :); then
        echo "$TAGS" | cut -d: -f2
    fi
}

rm -rf images/$NAME

for TAGS in $(getTags); do
    TAG=$(echo "${TAGS}" | cut -d: -f1)
    ALIASES=$(getAliases ${TAGS})
    IMGDIR="images/${SERVICE}/${TAG}"
    IMAGE="${FROM}:${TAG}"

    mkdir -p "${IMGDIR}"

    RUN=""
    if [ -e "${DIR}/run" ]; then
        cp "${DIR}/run" "${IMGDIR}/run"
        chmod +x "${IMGDIR}/run"
        RUN="RUN mkdir -p /etc/service/${NAME}\nCOPY run /etc/service/${NAME}/run"
    fi

    CUSTOM=/dev/null
    if [ -e "${DIR}/custom" ]; then
        CUSTOM="${DIR}/custom"
    fi

    if [ -e "${DIR}/files" ]; then
        cp -r "${DIR}/files" "${IMGDIR}/"
    fi

    cat Dockerfile.template | \
        sed "s|{{FROM}}|${IMAGE}|g" | \
        sed "/{{CUSTOM}}/ r ${CUSTOM}" | \
        sed "/{{CUSTOM}}/d" | \
        sed "s|{{RUN}}|${RUN}|g" \
        > "${IMGDIR}/Dockerfile"

    echo "${TAG}" > "${IMGDIR}/TAG"
    echo "${ALIASES}" > "${IMGDIR}/ALIASES"
    echo "${NAME}" > "${IMGDIR}/NAME"
done
