#!/usr/bin/env bash

DIR="images/$1"
# mkdir -p won't yell if the directory is there already.
mkdir -p "$DIR"

echo "## Supported Tags for tugboatqa/$1"
echo ""

cat ${DIR}/*/TAGS | sort -r | sed 's/\ /`,\ `/g' | sed 's/^/*\ `/g' | sed 's/$/`/g'

echo ""
echo "The above tags are currently supported. Visit https://hub.docker.com/r/tugboatqa/$1/tags/ to see a list of all available tags for this image, including those that are no longer supported."
