# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: 3

dotenv:
  - .env.local
  - .local.env
  - .env

vars:
  TARGETS:
    sh: find services -type d -maxdepth 1 -mindepth 1 -exec basename {} \;
  TASK_MINOR_VERSION:
    sh: echo "{{.TASK_VERSION}}" | awk -F'.' '{print $2}'

tasks:
  default:
    preconditions:
      - sh: 'test {{.TASK_MINOR_VERSION}} -ge 28'
        msg: 'Please upgrade Task to v3.28.0 or greater.'
    silent: true
    cmds:
      - for: { var: TARGETS }
        task: generate
        vars:
          SERVICEDIR: '{{.ITEM}}'
      - task: bake
      - task: build
      - task: push
      - task: manifest-create

  generate:
    vars:
      NAME:
        sh: |
          test -f services/{{.SERVICEDIR}}/manifest && source services/{{.SERVICEDIR}}/manifest
          (test -n "$NAME" && echo "$NAME") || (test -n "$SERVICE" && echo "$SERVICE") || echo "{{.SERVICEDIR}}"
    preconditions:
      - sh: 'test -n "{{.SERVICEDIR}}"'
        msg: 'Specify the directory name of the service with a SERVICEDIR environment variable.'
    status:
      - test -f images/{{.NAME}}/{{.SERVICEDIR}}
    cmds:
      - scripts/generate.sh {{.SERVICEDIR}}
      - touch images/{{.NAME}}/{{.SERVICEDIR}}

  bakefile:
    preconditions:
      - sh: 'test -d images'
        msg: 'Generate some Dockerfiles first using task generate.'
      - sh: 'command -v jq'
        msg: 'You must install jq.'
    sources:
      - images/*/*/Dockerfile
    generates:
      - bake.json
    cmds:
      - scripts/bakefile.sh
      - defer: rm -f newbake.json

  create-builder:
    deps:
      - buildkitd.toml
    status:
      - docker buildx ls | grep -q '^{{.BUILDX_BUILDER}}\s'
    cmds:
      - docker buildx create
          --name "{{.BUILDX_BUILDER}}"
          --config buildkitd.toml

  buildkitd.toml:
    status:
      - grep -q "max-parallelism = ${BUILDX_MAX_PARALLELISM}\$" buildkitd.toml
    sources:
      - templates/buildkitd.template.toml
    generates:
      - ./buildkitd.toml
    cmds:
      - envsubst < templates/buildkitd.template.toml > buildkitd.toml

  bake:
    preconditions:
      - sh: 'command -v jq'
        msg: 'You must install jq.'
    status:
      - test $(jq '.target | length' bake.json) -eq 0
    sources:
      - images/*/*/Dockerfile
    generates:
      - images/*/*/image.tar
    deps:
      - bakefile
      - create-builder
    cmds:
      - docker buildx bake --builder '{{.BUILDX_BUILDER}}' --file ./bake.json

  build:
    preconditions:
      - sh: 'test {{.TASK_MINOR_VERSION}} -ge 28'
        msg: 'Please upgrade Task to v3.28.0 or greater.'
    vars:
      IMAGES:
        # We loop over any image.tar files to be sure we only build images that
        # still need to be built.
        sh: for x in images/*/*/image.tar; do basename $(dirname $(dirname $x)); done | sort | uniq
    cmds:
      - 'parallel --jobs {{.PARALLEL_JOBS}} --retries 2 --bar --tag scripts/build.sh ::: {{.IMAGES}}'

  push:
    preconditions:
      - sh: 'test {{.TASK_MINOR_VERSION}} -ge 28'
        msg: 'Please upgrade Task to v3.28.0 or greater.'
      - sh: 'command -v parallel'
        msg: 'You must install GNU Parallel.'
    status:
      - test "$PUSH" != "true" && test "$PUSH" != "1"
    sources:
      - images/*/built/*
    generates:
      - images/*/pushed
    vars:
      IMAGES:
        sh: for x in images/*/built; do echo "$(basename $(dirname $x))"; done
    cmds:
      - 'parallel --jobs {{.PARALLEL_JOBS}} --retries 2 --bar --tag scripts/push.sh ::: {{.IMAGES}}'

  manifest-create:
    preconditions:
      - sh: 'test {{.TASK_MINOR_VERSION}} -ge 28'
        msg: 'Please upgrade Task to v3.28.0 or greater.'
    status:
      - test "$PUSH" != "true" && test "$PUSH" != "1"
    sources:
      - images/*/MANIFEST_LIST
    vars:
      MANIFEST_LISTS:
        sh: echo images/*/MANIFEST_LIST
    cmds:
      - for: { var: MANIFEST_LISTS }
        task: manifest-create-one
        vars:
          MANIFEST_LIST: '{{.ITEM}}'

  manifest-create-one:
    preconditions:
      - sh: test -n "{{.MANIFEST_LIST}}"
        msg: Specify the path to the manifest list you would like to create with MANIFEST_LIST variable.
      - sh: test -s "{{.MANIFEST_LIST}}"
        msg: The manifest list {{.MANIFEST_LIST}} does not exist or is empty.
    status:
      - test "$PUSH" != "true" && test "$PUSH" != "1"
    cmds:
      - scripts/manifest.sh {{.MANIFEST_LIST}}

  clean:
    preconditions:
      - sh: 'test {{.TASK_MINOR_VERSION}} -ge 28'
        msg: 'Please upgrade Task to v3.28.0 or greater.'
    vars:
      IMAGES:
        sh: for x in images/*; do echo "$(basename $x)"; done
    cmds:
      - for: { var: IMAGES, as: IMAGE }
        cmd: docker rmi --force $(docker images ls --filter=reference="{{.NAMESPACE}}/{{.IMAGE}}" -q | sort | uniq) || true
      - rm -f bake.json buildkitd.toml
      - rm -Rf images
