version: 3

vars:
    TARGETS:
        sh: find services -type d -maxdepth 1 -mindepth 1 -exec basename {} \;
    TASK_MINOR_VERSION:
        sh: echo "{{.TASK_VERSION}}" | awk -F'.' '{print $2}'

tasks:
    default:
        preconditions:
            - sh: 'test {{.TASK_MINOR_VERSION}} -ge 28'
        silent: true
        cmds:
            - for: { var: TARGETS }
              task: generate
              vars:
                  SERVICEDIR: '{{.ITEM}}'
            - task: bakefile

    generate:
        vars:
            NAME:
                sh: |
                    test -f services/{{.SERVICEDIR}}/manifest && source services/{{.SERVICEDIR}}/manifest
                    (test -n "$NAME" && echo "$NAME") || (test -n "$SERVICE" && echo "$SERVICE") || echo "{{.SERVICEDIR}}"
        preconditions:
            - sh: 'test -n "{{.SERVICEDIR}}"'
              msg: 'Specify the directory name of the service with a SERVICEDIR environment variable.'
        status:
            - test -f images/{{.NAME}}/{{.SERVICEDIR}}
        cmds:
            - scripts/generate.sh {{.SERVICEDIR}}
            - touch images/{{.NAME}}/{{.SERVICEDIR}}

    bakefile:
        preconditions:
            - sh: 'test -d images'
              msg: 'Generate some Dockerfiles first using task generate.'
        sources:
            - images/*/*/Dockerfile
        generates:
            - ./bake.json
        cmds:
            - scripts/bakefile.sh

    bake:
        deps:
            - bakefile
        cmds:
            - docker buildx bake --file ./bake.json
