FROM {{FROM}}

USER root

RUN --mount=type=cache,target=/var/cache/apk,sharing=locked \
    apk add --no-cache bash git openssh-client runit

{{DOCKERFILE}}

{{RUN}}

STOPSIGNAL SIGTERM

CMD ["/sbin/runsvdir", "-P", "/etc/service"]
