FROM {{FROM}}

USER root

RUN apk add --no-cache bash git openssh-client runit jq

{{DOCKERFILE}}

{{RUN}}

STOPSIGNAL SIGTERM

ENV RUNITDIR=

COPY runit-init.sh /runit-init.sh

CMD ["/runit-init.sh"]
